###### Site settings
title: Quanyin Blog
SEOTitle: Quanyin Tang的博客 | Quanyin Blog
header-img: /Source/images/background/bg-default.jpg    #默认底图,相对地址,如果没有额外指定的话,1900*870,渐进式jpg
email: qytang326@gmail.com
description: "博学而笃志，切问而近思 | 这里是 @Quanyin 的个人博客，与你一起发现更大的世界。"
keyword: "Quanyin, Quanyin Blog, Quanyin 博客, Quanyin Tang, Quanyin Tang的博客"
url: "https://quanyin.eu.org"                # your host, for absolute URL
#enforce_ssl: "quanyin.eu.org"
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog' /gh-pages-theme
homepage: "https://quanyin.eu.org"
repo: qytang326.github.io                      #Where is the Repo

##### Build settings
encoding: utf-8
highlighter: rouge
permalink: /:year/:month/:day/:title/      #自定义永久链接,或者使用#permalink: pretty
paginate: 10                                    #每页展示项目数
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html` 取消#显示
### Gems
plugins: 
  - github-pages
  - jekyll-paginate
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-gist  
  - jekyll-feed
#  - jemoji

### Markdown settings
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important


#### 插件设置与开关 
### Sidebar settings 侧边栏
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "自由而无用的灵魂，<br>离开世界之前，一切都是过程"
sidebar-avatar: /Source/images/avatar.jpg  # use absolute URL, seeing it's used in both `/` and `/about/`
catalog: true                           # 文章侧边栏目录
keynote-catalog: false
### Featured Tags 推荐Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 2              # A tag will be featured if the size of it is more than this condition value
## Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

### BGM in Page About Me
BGM: true
## 网易云音乐   8月24日：弃用,效果不好，改用Aplayer
#netease-music: false
#netease-music_url: "//music.163.com/outchain/player?type=0&id=804530027&auto=1&height=430"
## APlayer，Doc: https://aplayer.js.org/docs/#/?id=options && https://www.tiexo.cn/aplayer/ https://api.i-meto.com/music/player.js
APlayer: 
    data-id: 804530027      #歌曲/专辑/歌单ID
    data-server: netease    #可选参数 netease(网易云音乐)tencent(qq音乐)xiami(虾米音乐)kugou(酷狗音乐)baidu(百度音乐)
    data-type: playlist     #类型:song/album/playlist/search
    data-mode: random       #播放模式:random/single/circulation/order
    data-autoplay: true     #自动播放true or false
##不蒜子计数
busuanzi: true
busuanzi_fixcount: true #初始数值修正
##pageviews
hit-kounter: false
##页面点击小红心
click-love: true
##背景动画-特效
canvas-nest: false
###推送到百度、360等以增加收录
push-for-include: false
##百度 需要验证
push-to-baidu: false
##360
push-to-360: false


#### 以下内容需要个人信息
# SNS settings 具体设置见_include/footer.html
RSS: false           #RSS: feed.xml
weibo_username:     778950326
zhihu_username:     qytang326
github_username:    qytang326
#twitter_username:   
#facebook_username:  
linkedin_username:  quanyin-tang-56a543b1

### 评论系统 具体设置与格式在_layout/post.html
# Disqus settings 
#disqus_username: qytang326
# Netease setttings 
netease_comment: false
# Gitment settings
Gitment: true
repo_for_gitment: Blog-Comment                  # 存放Issue的地方
oauth_client_id: 9cb56c7c83cee1f4ecc4           #Gihub OAuth的 client ID,与CNAME有关
oauth_client_secret: 1707226acc63d5fcd7639d82682fe3afa3a9129e   #Gihub OAuth的 client secret
#daovoice
daovoice: false
daovoice_appid: f72737da
daovoice_userid: NO_89757


### 统计与分析 Analytics settings
# Baidu Analytics 
#ba_track_id: 'a9b724867d3ace8e123ba004607207f2'
# Google Analytics
ga_track_id: 'UA-105172812-1'            # Format: UA-xxxxxx-xx
ga_domain: auto                         #  自定义的域名,默认的是 auto,
## 站点验证 html标记
#baidu-site-verification: "0H5CdgBtg0"       #origin,与域名有关,在_include/head.html中,下同  
#baidu-site-verification: aNsquf4NVy
google-site-verification: KIjjnGZK8x7PddQoXqhBJrOpbYg7k04AHE_gt_1PYtc 

# Friends
friends: [
    {
         title: "Quanyin",
         href: "https://qytang326.github.io/"
    },
    {
         title: "Hux Blog",
         href: "https://huangxuan.me/"
    },
    {   
         title: "BruceZhaoR",
         href: "http://brucezhaor.github.io"
    },
    {   
         title: "CCMG",
         href: "https://fudanccmg.github.io"
    },
    {   
         title: "阮一峰的网络日志",
         href: "http://www.ruanyifeng.com/blog/"
    },
    {   
         title: "不二侬",
         href: "http://buer.website/pc.html"
    },
    {   
         title: "时间的朋友",
         href: "http://51world.win/"
    },
    {   
         title: "廖雪峰的官方网站",
         href: "https://www.liaoxuefeng.com/"
    },
    {   
         title: "小众软件",
         href: "http://www.appinn.com/"
    },
    {   
         title: "月光博客",
         href: "http://williamlong.info/"
    },
]
